name: Docker Bun CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-test-production:
    name: Build, Test, and Production Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build development image
        run: docker build --target=dev -t bun-app-dev .

      - name: Build and run tests
        run: |
          docker compose --env-file .env.test --profile test up --build --abort-on-container-exit test

      - name: Build production image
        run: docker build --target=production -t bun-app-prod .

  test-on-dev:
    name: Test on Dev Branch
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env.test file
        run: |
          echo "NODE_ENV=test" > .env.test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build development image
        run: docker build --target=dev -t bun-app-dev .

      - name: Build and run tests
        run: |
          docker compose --env-file .env.test --profile test up --build --abort-on-container-exit test
