name: Bun Docker CI/CD

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  ci-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env.test file
        run: echo "NODE_ENV=test" > .env.test

      - name: Run tests inside Docker container
        run: |
          docker compose --env-file .env.test --profile test up --build --abort-on-container-exit test

  build-and-push-production:
    needs: ci-build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env.production file
        run: echo "NODE_ENV=production" > .env.production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build production image
        run: docker build --target=production -t bun-app-prod .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag and push image to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          IMAGE_NAME=${DOCKERHUB_USERNAME}/bun-app-prod
          docker tag bun-app-prod $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
